apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-custom-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: standalone-nginx
  template:
    metadata:
      labels:
        app: standalone-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
