apiVersion: v1
kind: Service
metadata:
  name: my-node-service-app
spec:
  selector:
    app: node-app
  ports:
    - name: http
      port: 80        # External port
      targetPort: 3000 # Pod's container port
  type: LoadBalancer
