# we are using a multi-container in a single pod deployment
# reqirements:
# 1. Node.js application container 
# 2. MongoDB container
# 3. Both containers should be in the same pod

# deployment: ------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-db-in-multi-pod   # Unique name for the Deployment
spec:
  replicas: 2      # 2 Pods at all times
  selector:
    matchLabels:
      app: mongo-app   # Match the app label
  template:
    metadata:
      labels:
        app: mongo-app # Pod label must match selector
    spec:
      containers:
        - name: mongo-app
          image: philippaul/node-mongo-db:02  # Replace this
        - name: mongodb
          image: mongo:latest  # MongoDB container

---

# service: ------------------------------------------
apiVersion: v1  
kind: Service
metadata:
  name: my-node-db-in-multi-pod-service
spec:
  selector:
    app: mongo-app   # Match the app label
  ports:
    - name: http
      port: 8080       # Port on which the service will be exposed
      targetPort: 3000 # Port on the container to forward traffic to
  type: NodePort       # Expose the service on a port on each Node in the cluster


  