# deployment of the mongo app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app # Unique name for the Deployment
spec:
  replicas: 1 # 2 Pods at all times
  selector:
    matchLabels:
      app: mongo-app # Match the app label
  template:
    metadata:
      labels:
        app: mongo-app # Pod label must match selector
    spec:
     containers: # Container definition
       - name: mongo-app
         image: mongo:latest # MongoDB container
         volumeMounts:
          - mountPath: /data/db
            name: mongo-vol # Persistent volume name
     volumes:
       - name: mongo-vol
         persistentVolumeClaim:
          claimName: host-pvc # Name of the PersistentVolumeClaim to use


---
# service for the mongo app
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb # Unique name for the Service
spec:
  selector:
    app: mongo-app # Match the app label
  ports:
    - name: tcp
      port: 27017 # Port on which the service will be exposed
      targetPort: 27017 # Port on the container to forward traffic to
  type: NodePort # Expose the service on a port on each Node in the cluster


