# configmap:
apiVersion: v1  
kind: ConfigMap
metadata:
  name: mongo-config
data: 
  MONGO_HOST: "service-mongodb"  # Name of the MongoDB service
  MONGO_PORT: "27017"             # Default MongoDB port